security:

    providers:
         app_user_provider:
              id: app.security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/login$
            anonymous: ~

        secured_area:
            pattern:    ^/
            simple_form:
                login_path: login
                check_path: login_check
                provider: app_user_provider
                authenticator: app.security.authenticator
                csrf_provider: form.csrf_provider
            logout:
                path:   logout
                target: home
            remember_me:
                key:      "%secret%"
                lifetime: 3600 # 1 hour in seconds
                path:     /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

