home:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

lost_password:
    path:     /lost-password
    defaults: { _controller: AppBundle:Security:lost-password }

reset_password:
    path:     /reset-password
    defaults: { _controller: AppBundle:Security:reset-password }

login_check:
    path: /login-check

logout:
    path: /logout

users_list:
  path:     /users
  defaults: { _controller: AppBundle:Users:list }

users_new:
  path:     /users/new
  defaults: { _controller: AppBundle:Users:new }

users_show:
  path:     /users/{user_key}
  defaults: { _controller: AppBundle:Users:show }
